from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine


BASE_DIR = Path(__file__).resolve().parents[2]


class Settings(BaseSettings):
    database_url: str

    model_config = SettingsConfigDict(
        env_file=BASE_DIR / ".env",
        extra="ignore",
    )


settings = Settings()

DATABASE_URL = settings.database_url

engine: Engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
)


def get_connection():
    return engine.connect()


def init_db():
    with engine.begin() as conn:
        conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    role TEXT NOT NULL
                        CHECK(role IN ('ADMIN','MANAGER','AUDITOR','USER'))
                );

                CREATE TABLE IF NOT EXISTS assets (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    asset_code TEXT NOT NULL UNIQUE,
                    name TEXT NOT NULL,
                    serial_number TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'ACTIVE',
                    owner_id INTEGER,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY(owner_id) REFERENCES users(id)
                );

                CREATE TABLE IF NOT EXISTS transfers (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    asset_id INTEGER NOT NULL,
                    from_owner_id INTEGER,
                    to_owner_id INTEGER NOT NULL,
                    transferred_by_role TEXT NOT NULL,
                    transferred_by_name TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY(asset_id) REFERENCES assets(id),
                    FOREIGN KEY(from_owner_id) REFERENCES users(id),
                    FOREIGN KEY(to_owner_id) REFERENCES users(id)
                );

                CREATE TABLE IF NOT EXISTS audit_logs (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actor_role TEXT NOT NULL,
                    actor_name TEXT NOT NULL,
                    action TEXT NOT NULL,
                    asset_id INTEGER,
                    details TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY(asset_id) REFERENCES assets(id)
                );
                """
            )
        )

        demo_users = [
            ("Aditi Admin", "admin@bel.demo", "ADMIN"),
            ("Mohan Manager", "manager@bel.demo", "MANAGER"),
            ("Ananya Auditor", "auditor@bel.demo", "AUDITOR"),
            ("Rahul User", "user@bel.demo", "USER"),
            ("Priya User", "priya@bel.demo", "USER"),
        ]

        for name, email, role in demo_users:
            conn.execute(
                text(
                    """
                    INSERT INTO users (name, email, role)
                    VALUES (:name, :email, :role)
                    ON CONFLICT (email) DO NOTHING
                    """
                ),
                {"name": name, "email": email, "role": role},
            )